### ISSUE TITLE
Dialogue client generation fails if doc string contains the `$` symbol

### ISSUE THREAD

**Issue by afloren** [palantir/conjure-java#901]
## What happened?

If a doc string contains the `$` symbol then code generation will fail.

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.palantir.conjure.java.cli.ConjureJavaCli$GenerateCommand@1bb5a082): java.lang.IllegalArgumentException: index 1 for '$i' not in range (received 0 arguments)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
        at picocli.CommandLine.run(CommandLine.java:2807)
        at picocli.CommandLine.run(CommandLine.java:2744)
        at com.palantir.conjure.java.cli.ConjureJavaCli.main(ConjureJavaCli.java:48)
  Caused by: java.lang.IllegalArgumentException: index 1 for '$i' not in range (received 0 arguments)
        at com.squareup.javapoet.Util.checkArgument(Util.java:53)
        at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:287)
        at com.squareup.javapoet.TypeSpec$Builder.addJavadoc(TypeSpec.java:439)
        at com.palantir.conjure.java.services.dialogue.DialogueEndpointsGenerator.lambda$endpointField$1(DialogueEndpointsGenerator.java:82)
```

Can be reproduced by adding a `$` symbol to any doc string.

## What did you want to happen?

Client generation should be consistent with other generators.

**Comment by Alexis-D** [comment]
@carterkozak I think this is still broken when documenting endpoints themselves, e.g.:

```
services:
  FooService:
    endpoints:
      doSomething:
        http: POST /do-something
        docs: does $something
```

fails with a similar stacktrace.

**Comment by carterkozak** [comment]
release incoming shortly: #974
